### ISSUE TITLE
Tags helpers won't work for multiple collections

### ISSUE THREAD

**Issue by apendua** [apendua/meteor-tags#3]
Currently, if event you add `TagsMixin` to multiple collection (which is totally fine), the rendering helpers will only work with the first collection.

**Comment by wizonesolutions** [comment]
Is there a workaround? Can you manually render the other ones?

**Comment by apendua** [comment]
@wizonesolutions I'm afraid there is no easy workaround :/ Though, this problem is quite is easy to fix. If I'm lucky, I should be able to commit some patches even today.

**Comment by wizonesolutions** [comment]
That'd be neat. Building an app that needs tags, and it'd be nice to use a smart package instead of rolling my own :) Thanks for the quick reply!

**Comment by apendua** [comment]
@wizonesolutions I hope this should work now.

**Comment by wizonesolutions** [comment]
Is the implementation method still the same? https://github.com/apendua/meteor-tags/blob/master/README.md. Calling Tags.TagsMixIn and passing the collection.

**Comment by apendua** [comment]
Ups, I haven't mentioned it in docs. To render tags for a non default collection (default is always the first collection for which you call `Tags.TagMixin`) you need to provide collection name like this:

``` html
{{renderTags 'myCollection'}}
```

Also, there is no longer `{{addTagButton}}` helper. The button is always included in the rendered list. Maybe later we will make this behavior configurable. Another minor API change is that the `tagName` is now the first argument of `addTag` and `removeTag` routine.

@wizonesolutions please let me know if you manage to make everything work :)

**Comment by wizonesolutions** [comment]
You mean that `{{renderTags 'mycollection'}}` will always render the button? I guess I can `display: none` it in the worst case.

Am I right about calling `Tags.TagMixin` multiple times for different collections though?

**Comment by apendua** [comment]
@wizonesolutions Yes, you're right about the mixin.
